export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_DASHBOARD_SUCCESS = "LOAD_DASHBOARD_SUCCESS";

export const LOAD_TRACKINGS_SUCCESS = "LOAD_TRACKINGS_SUCCESS";
export const CREATE_TRACKING_SUCCESS = "CREATE_TRACKING_SUCCESS";
export const UPDATE_TRACKING_SUCCESS = "UPDATE_TRACKING_SUCCESS";
export const DELETE_TRACKING_SUCCESS = "DELETE_TRACKING_SUCCESS";

export const LOAD_ASSETS_SUCCESS = "LOAD_ASSETS_SUCCESS";
export const CREATE_ASSET_SUCCESS = "CREATE_ASSET_SUCCESS";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";

